// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqr8IUCTq6MjJa9eIcGvbKyX2842qLe2U',
    appId: '1:886096983718:web:8bfc166d37a12ef095a667',
    messagingSenderId: '886096983718',
    projectId: 'ulam-30574',
    authDomain: 'ulam-30574.firebaseapp.com',
    storageBucket: 'ulam-30574.appspot.com',
    measurementId: 'G-5L51E0VSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pbVu7zwb-pP-LBej_3nV5xi2Mt5zVkE',
    appId: '1:886096983718:android:805fe77ccde4e31d95a667',
    messagingSenderId: '886096983718',
    projectId: 'ulam-30574',
    storageBucket: 'ulam-30574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKafMJYleyIqR9yXrh3Bv9WYQ7KTbVr94',
    appId: '1:886096983718:ios:5208542fba2831bf95a667',
    messagingSenderId: '886096983718',
    projectId: 'ulam-30574',
    storageBucket: 'ulam-30574.appspot.com',
    iosClientId: '886096983718-8p8et659it9lkqo9b2vkm11vva3cfuek.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulamLands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKafMJYleyIqR9yXrh3Bv9WYQ7KTbVr94',
    appId: '1:886096983718:ios:5208542fba2831bf95a667',
    messagingSenderId: '886096983718',
    projectId: 'ulam-30574',
    storageBucket: 'ulam-30574.appspot.com',
    iosClientId: '886096983718-8p8et659it9lkqo9b2vkm11vva3cfuek.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulamLands',
  );
}
